### ISSUE TITLE
flickr2ia.py - Downloads stop randomly

### ISSUE THREAD

**Issue by qw3rty2017** [emijrp/internet-archive#1]
Does the script not retry to download images?

```
Downloading https://farm6.staticflickr.com/5542/11017993423_77ddee8a7f_o.jpg
Traceback (most recent call last):
  File "./flickr2ia.py", line 460, in <module>
    main()
  File "./flickr2ia.py", line 362, in main
    download(url=photoprops['url_o'], filename=photofilename)
  File "./flickr2ia.py", line 218, in download
    urllib.request.urlretrieve(url, filename)
  File "/usr/lib/python3.5/urllib/request.py", line 229, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 10370148 out of 19867683 bytes>
```

**Comment by emijrp** [comment]
Try --resume option
